services:
  product-db:
    image: postgres:latest
    container_name: product-db
    environment:
      POSTGRES_USER: marko09
      POSTGRES_PASSWORD: haslo1
      POSTGRES_DB: product-db
    ports:
      - "5432:5432"
    volumes:
      - product-db-data:/var/lib/postgresql/data
    networks:
      - online-shop

  cart-db:
    image: postgres:latest
    container_name: cart-db
    environment:
      POSTGRES_DB: cart-db
      POSTGRES_USER: marko09
      POSTGRES_PASSWORD: haslo1
    ports:
      - "5433:5432"
    volumes:
      - cart-db-data:/var/lib/postgresql/data
    networks:
      - online-shop

  order-db:
    image: postgres:latest
    container_name: order-db
    environment:
      POSTGRES_DB: order-db
      POSTGRES_USER: marko09
      POSTGRES_PASSWORD: haslo1
    ports:
      - "5434:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data
    networks:
      - online-shop

  pgadmin0:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: marko9@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin11
    ports:
      - "8081:80"
    depends_on:
      - product-db
      - cart-db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - online-shop

volumes:
  product-db-data:
  cart-db-data:
  order-db-data:
  pgadmin_data:

networks:
  online-shop: